version: "3.1"

recipe: default.v1
language: en

pipeline:
  # Tokenization
- name: WhitespaceTokenizer

  # Feature extraction
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer

  # Text vectorization
- name: CountVectorsFeaturizer
  analyzer: "word"
  min_ngram: 1
  max_ngram: 2
  stop_words: "english"
- name: CountVectorsFeaturizer
  analyzer: "char_wb"
  min_ngram: 2
  max_ngram: 4

  # Intent classification
- name: DIETClassifier
  epochs: 200
  hidden_layers_sizes:
    text: [256, 128]
  embedding_dimension: 50
  constrain_similarities: true
  dropout: 0.2
  learning_rate: 0.0005
  batch_size: [32, 64]
  batch_strategy: "balanced"
  evaluation_epochs: 10
  entity_recognition: true
  use_masked_language_model: true

  # Response Selector
- name: ResponseSelector
  epochs: 100
  hidden_layers_sizes:
    text: [256, 128]
  batch_size: [32, 64]
  constrain_similarities: true
  learning_rate: 0.001

  # Fallback handling
- name: FallbackClassifier
  threshold: 0.3
  ambiguity_threshold: 0.1

policies:
  # Core policies
- name: MemoizationPolicy
  max_history: 5

- name: RulePolicy
  core_fallback_threshold: 0.4
  core_fallback_action_name: "action_default_fallback"
  enable_fallback_prediction: true
  restrict_rules: true

- name: TEDPolicy
  max_history: 7
  epochs: 150
  hidden_layers_sizes:
    text: [256, 128]
    action: [128, 64]
  batch_size: [32, 64]
  learning_rate: 0.001
  dropout: 0.2
  constrain_similarities: true
  use_gpu: true

- name: UnexpecTEDIntentPolicy
  max_history: 5
  epochs: 100
  constrain_similarities: true
  learning_rate: 0.001

assistant_id: 20250328-125607-cream-congruence
