version: "3.1"

recipe: default.v1
language: en

pipeline:
  # Tokenization
  - name: WhitespaceTokenizer
  
  # Feature extraction
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer

  # Text vectorization (optimized settings)
  - name: CountVectorsFeaturizer
    analyzer: "word"
    min_ngram: 1
    max_ngram: 2
    stop_words: "english"  # Added stop words removal
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 2
    max_ngram: 4

  # Intent classification with improved DIET
  - name: DIETClassifier
    epochs: 150
    hidden_layers_sizes:
      text: [256, 128]
    embedding_dimension: 50
    constrain_similarities: true  # Enabled similarity constraints
    dropout: 0.2
    learning_rate: 0.001
    batch_size: [32, 64]
    batch_strategy: "balanced"
    evaluation_epochs: 10
    entity_recognition: true  # Explicitly enabled
    use_masked_language_model: true  # Added masked language model

  # Enhanced Response Selector
  - name: ResponseSelector
    epochs: 100
    hidden_layers_sizes:
      text: [256, 128]
    batch_size: [32, 64]
    constrain_similarities: true  # Added similarity constraints
    learning_rate: 0.001

  # Fallback handling with tuned thresholds
  - name: FallbackClassifier
    threshold: 0.35
    ambiguity_threshold: 0.15

policies:
  # Memorization policy with adjusted history
  - name: MemoizationPolicy
    max_history: 5

  # Rule policy with optimized settings
  - name: RulePolicy
    core_fallback_threshold: 0.4
    core_fallback_action_name: "action_default_fallback"
    enable_fallback_prediction: true
    restrict_rules: true  # Added rule restriction

  # Enhanced TED Policy
  - name: TEDPolicy
    max_history: 7
    epochs: 150
    hidden_layers_sizes:
      text: [256, 128]
      action: [128, 64]
    batch_size: [32, 64]
    learning_rate: 0.001
    dropout: 0.2
    constrain_similarities: true  # Added similarity constraints
    use_gpu: true  # Enable GPU if available

  # Unexpected intent policy with similarity constraints
  - name: UnexpecTEDIntentPolicy
    max_history: 5
    epochs: 100
    constrain_similarities: true  # Added similarity constraints
    learning_rate: 0.001

assistant_id: 20250326-152333-stable-octave